import type {
  FollowUp,
  Lead,
  SiteVisit,
  TimelineEvent,
} from "@/lib/types";

export const TODAY = new Date("2026-06-21T09:00:00");

export const EXECUTIVES = [
  "Bharath Kumar",
  "Yamini Sridhar",
  "Praveen Anand",
  "Shobana Murali",
  "Dinesh Kannan",
] as const;

export const LEAD_SOURCES = [
  "Facebook Ads",
  "Google Ads",
  "Walk-in",
  "Referral",
  "Website",
  "WhatsApp",
] as const;

export const LEAD_STATUSES = [
  "New",
  "Interested",
  "Follow-up",
  "Site Visit",
  "Won",
  "Lost",
] as const;

function tl(
  id: string,
  type: TimelineEvent["type"],
  title: string,
  description: string,
  timestamp: string
): TimelineEvent {
  return { id, type, title, description, timestamp };
}

export const LEADS: Lead[] = [
  {
    id: "lead-1",
    name: "Karthik Subramaniam",
    phone: "+91 98765 43210",
    email: "karthik.subramaniam@gmail.com",
    location: "Saravanampatti",
    source: "Facebook Ads",
    status: "Site Visit",
    assignedTo: "Bharath Kumar",
    enquiry: "3BHK villa enquiry - Saravanampatti",
    createdAt: "2026-06-05",
    lastFollowUp: "2026-06-19",
    nextFollowUp: "2026-06-23",
    timeline: [
      tl("l1-1", "note", "Lead captured", "Lead captured from Facebook Ads campaign", "2026-06-05T09:15:00"),
      tl("l1-2", "call", "Call made", "Discussed 3BHK villa requirements and budget (₹85L-95L)", "2026-06-07T11:00:00"),
      tl("l1-3", "followup", "Follow-up added", "Shared villa brochure and floor plans via WhatsApp", "2026-06-12T15:30:00"),
      tl("l1-4", "note", "Note added", "Client confirmed interest, wants to see model unit", "2026-06-16T10:00:00"),
      tl("l1-5", "site-visit", "Site visit scheduled", "Scheduled site visit for Saravanampatti villa project on 23 Jun", "2026-06-19T17:00:00"),
    ],
  },
  {
    id: "lead-2",
    name: "Priya Venkatesh",
    phone: "+91 98421 11234",
    email: "priya.venkatesh@gmail.com",
    location: "RS Puram",
    source: "Referral",
    status: "Won",
    assignedTo: "Yamini Sridhar",
    enquiry: "2BHK apartment - RS Puram resale",
    createdAt: "2026-05-20",
    lastFollowUp: "2026-06-15",
    nextFollowUp: null,
    timeline: [
      tl("l2-1", "note", "Lead captured", "Referral from existing client", "2026-05-20T10:00:00"),
      tl("l2-2", "call", "Call made", "Discussed 2BHK resale options in RS Puram", "2026-05-23T12:00:00"),
      tl("l2-3", "site-visit", "Site visit completed", "Visited the RS Puram flat, client impressed", "2026-06-02T16:00:00"),
      tl("l2-4", "followup", "Follow-up added", "Negotiating final price with owner", "2026-06-10T14:00:00"),
      tl("l2-5", "status", "Marked as Won", "Deal closed at ₹62L", "2026-06-15T11:30:00"),
    ],
  },
  {
    id: "lead-3",
    name: "Arun Raj",
    phone: "+91 99440 22456",
    email: "arun.raj@gmail.com",
    location: "Peelamedu",
    source: "Google Ads",
    status: "Interested",
    assignedTo: "Praveen Anand",
    enquiry: "Full home interior - Peelamedu",
    createdAt: "2026-06-10",
    lastFollowUp: "2026-06-18",
    nextFollowUp: "2026-06-22",
    timeline: [
      tl("l3-1", "note", "Lead captured", "Enquiry via Google Ads for home interiors", "2026-06-10T09:30:00"),
      tl("l3-2", "call", "Call made", "Understood requirement for full home interior, 3BHK", "2026-06-12T13:00:00"),
      tl("l3-3", "followup", "Follow-up added", "Shared interior design portfolio and pricing tiers", "2026-06-18T15:00:00"),
    ],
  },
  {
    id: "lead-4",
    name: "Lakshmi Narayanan",
    phone: "+91 97890 33678",
    email: "lakshmi.narayanan@gmail.com",
    location: "Singanallur",
    source: "Walk-in",
    status: "Follow-up",
    assignedTo: "Shobana Murali",
    enquiry: "Wardrobe + false ceiling - Singanallur",
    createdAt: "2026-06-08",
    lastFollowUp: "2026-06-17",
    nextFollowUp: "2026-06-21",
    timeline: [
      tl("l4-1", "note", "Lead captured", "Walk-in enquiry at showroom", "2026-06-08T11:00:00"),
      tl("l4-2", "call", "Call made", "Discussed wardrobe and false ceiling requirements", "2026-06-10T14:30:00"),
      tl("l4-3", "followup", "Follow-up added", "Sent quotation for modular wardrobe", "2026-06-17T10:00:00"),
      tl("l4-4", "note", "Note added", "Client comparing with another vendor", "2026-06-19T16:00:00"),
    ],
  },
  {
    id: "lead-5",
    name: "Mohammed Faizal",
    phone: "+91 90030 44890",
    email: "mohammed.faizal@gmail.com",
    location: "Race Course",
    source: "Website",
    status: "Site Visit",
    assignedTo: "Dinesh Kannan",
    enquiry: "Villa interior design - Race Course",
    createdAt: "2026-06-02",
    lastFollowUp: "2026-06-19",
    nextFollowUp: "2026-06-24",
    timeline: [
      tl("l5-1", "note", "Lead captured", "Enquiry via website for villa interiors", "2026-06-02T10:00:00"),
      tl("l5-2", "call", "Call made", "Discussed design themes and budget", "2026-06-05T12:30:00"),
      tl("l5-3", "followup", "Follow-up added", "Shared 3D renders of living room concept", "2026-06-14T15:00:00"),
      tl("l5-4", "site-visit", "Site visit scheduled", "Scheduled material sample walkthrough on 24 Jun", "2026-06-19T17:30:00"),
    ],
  },
  {
    id: "lead-6",
    name: "Divya Shankar",
    phone: "+91 94430 55012",
    email: "divya.shankar@gmail.com",
    location: "Saibaba Colony",
    source: "WhatsApp",
    status: "New",
    assignedTo: "Bharath Kumar",
    enquiry: "3BHK flat - Saibaba Colony, ready to move",
    createdAt: "2026-06-20",
    lastFollowUp: null,
    nextFollowUp: "2026-06-22",
    timeline: [
      tl("l6-1", "note", "Lead captured", "Enquiry via WhatsApp for ready-to-move 3BHK flat", "2026-06-20T09:00:00"),
    ],
  },
  {
    id: "lead-7",
    name: "Senthil Kumar",
    phone: "+91 98765 66234",
    email: "senthil.kumar@gmail.com",
    location: "Saravanampatti",
    source: "Facebook Ads",
    status: "Lost",
    assignedTo: "Yamini Sridhar",
    enquiry: "Plot enquiry - Saravanampatti",
    createdAt: "2026-05-15",
    lastFollowUp: "2026-06-01",
    nextFollowUp: null,
    timeline: [
      tl("l7-1", "note", "Lead captured", "Facebook Ads enquiry for residential plot", "2026-05-15T10:00:00"),
      tl("l7-2", "call", "Call made", "Discussed plot size and pricing", "2026-05-18T12:00:00"),
      tl("l7-3", "followup", "Follow-up added", "Client said budget mismatch", "2026-06-01T11:00:00"),
      tl("l7-4", "status", "Marked as Lost", "Client purchased plot elsewhere", "2026-06-01T11:05:00"),
    ],
  },
  {
    id: "lead-8",
    name: "Revathi Ramesh",
    phone: "+91 99765 77345",
    email: "revathi.ramesh@gmail.com",
    location: "Vadavalli",
    source: "Referral",
    status: "Follow-up",
    assignedTo: "Praveen Anand",
    enquiry: "Independent house - Vadavalli, budget 80L",
    createdAt: "2026-06-11",
    lastFollowUp: "2026-06-19",
    nextFollowUp: "2026-06-20",
    timeline: [
      tl("l8-1", "note", "Lead captured", "Referral enquiry for independent house", "2026-06-11T09:30:00"),
      tl("l8-2", "call", "Call made", "Discussed budget of ₹80L and loan options", "2026-06-13T13:00:00"),
      tl("l8-3", "followup", "Follow-up added", "Awaiting bank pre-approval documents", "2026-06-19T15:30:00"),
    ],
  },
  {
    id: "lead-9",
    name: "Vignesh Anand",
    phone: "+91 96290 88456",
    email: "vignesh.anand@gmail.com",
    location: "Ganapathy",
    source: "Google Ads",
    status: "New",
    assignedTo: "Shobana Murali",
    enquiry: "Renovation - kitchen + living room, Ganapathy",
    createdAt: "2026-06-19",
    lastFollowUp: null,
    nextFollowUp: "2026-06-23",
    timeline: [
      tl("l9-1", "note", "Lead captured", "Google Ads enquiry for kitchen and living room renovation", "2026-06-19T10:00:00"),
    ],
  },
  {
    id: "lead-10",
    name: "Kavitha Raman",
    phone: "+91 97150 99567",
    email: "kavitha.raman@gmail.com",
    location: "Saravanampatti",
    source: "Website",
    status: "Site Visit",
    assignedTo: "Dinesh Kannan",
    enquiry: "4BHK villa - gated community, Saravanampatti",
    createdAt: "2026-06-04",
    lastFollowUp: "2026-06-18",
    nextFollowUp: "2026-06-25",
    timeline: [
      tl("l10-1", "note", "Lead captured", "Website enquiry for 4BHK villa", "2026-06-04T09:00:00"),
      tl("l10-2", "call", "Call made", "Discussed gated community amenities", "2026-06-07T11:30:00"),
      tl("l10-3", "followup", "Follow-up added", "Shared community master plan and pricing sheet", "2026-06-15T14:00:00"),
      tl("l10-4", "site-visit", "Site visit scheduled", "Confirmed site tour for 25 Jun", "2026-06-18T16:30:00"),
    ],
  },
  {
    id: "lead-11",
    name: "Suresh Babu",
    phone: "+91 98430 10678",
    email: "suresh.babu@gmail.com",
    location: "Peelamedu",
    source: "Walk-in",
    status: "Interested",
    assignedTo: "Bharath Kumar",
    enquiry: "Studio apartment - investment, Peelamedu",
    createdAt: "2026-06-13",
    lastFollowUp: "2026-06-19",
    nextFollowUp: "2026-06-24",
    timeline: [
      tl("l11-1", "note", "Lead captured", "Walk-in enquiry for investment studio apartment", "2026-06-13T10:30:00"),
      tl("l11-2", "call", "Call made", "Discussed rental yield expectations", "2026-06-16T12:00:00"),
      tl("l11-3", "followup", "Follow-up added", "Shared comparison of 2 studio unit options", "2026-06-19T15:00:00"),
    ],
  },
  {
    id: "lead-12",
    name: "Anitha Krishnan",
    phone: "+91 90420 21789",
    email: "anitha.krishnan@gmail.com",
    location: "Singanallur",
    source: "WhatsApp",
    status: "Won",
    assignedTo: "Yamini Sridhar",
    enquiry: "Turnkey interior - 2BHK, Singanallur",
    createdAt: "2026-05-25",
    lastFollowUp: "2026-06-14",
    nextFollowUp: null,
    timeline: [
      tl("l12-1", "note", "Lead captured", "WhatsApp enquiry for turnkey 2BHK interior", "2026-05-25T09:00:00"),
      tl("l12-2", "call", "Call made", "Discussed turnkey package inclusions", "2026-05-28T11:00:00"),
      tl("l12-3", "site-visit", "Site visit completed", "Measurement and layout finalized", "2026-06-10T13:00:00"),
      tl("l12-4", "followup", "Follow-up added", "Final agreement signed", "2026-06-14T10:00:00"),
      tl("l12-5", "status", "Marked as Won", "Project confirmed, work order issued", "2026-06-14T10:10:00"),
    ],
  },
  {
    id: "lead-13",
    name: "Naveen Prakash",
    phone: "+91 95000 32890",
    email: "naveen.prakash@gmail.com",
    location: "RS Puram",
    source: "Facebook Ads",
    status: "Follow-up",
    assignedTo: "Praveen Anand",
    enquiry: "Resale flat enquiry - RS Puram",
    createdAt: "2026-06-09",
    lastFollowUp: "2026-06-16",
    nextFollowUp: "2026-06-19",
    timeline: [
      tl("l13-1", "note", "Lead captured", "Facebook Ads enquiry for resale flat", "2026-06-09T10:00:00"),
      tl("l13-2", "call", "Call made", "Discussed flat specifications and price", "2026-06-12T12:30:00"),
      tl("l13-3", "followup", "Follow-up added", "Requested resale documents from owner", "2026-06-16T14:30:00"),
    ],
  },
  {
    id: "lead-14",
    name: "Meena Sundaram",
    phone: "+91 93450 43901",
    email: "meena.sundaram@gmail.com",
    location: "Race Course",
    source: "Referral",
    status: "Site Visit",
    assignedTo: "Shobana Murali",
    enquiry: "NRI client - full villa interior, Race Course",
    createdAt: "2026-06-06",
    lastFollowUp: "2026-06-20",
    nextFollowUp: "2026-06-26",
    timeline: [
      tl("l14-1", "note", "Lead captured", "Referral enquiry, NRI client based in Dubai", "2026-06-06T08:30:00"),
      tl("l14-2", "call", "Call made", "Video call to discuss design preferences", "2026-06-09T13:00:00"),
      tl("l14-3", "followup", "Follow-up added", "Shared mood boards over email", "2026-06-15T15:30:00"),
      tl("l14-4", "note", "Note added", "Client family available for on-site visit during their India trip", "2026-06-20T09:00:00"),
      tl("l14-5", "site-visit", "Site visit scheduled", "Scheduled in-person + virtual walkthrough on 26 Jun", "2026-06-20T09:10:00"),
    ],
  },
  {
    id: "lead-15",
    name: "Rajesh Gounder",
    phone: "+91 96000 54012",
    email: "rajesh.gounder@gmail.com",
    location: "Town Hall",
    source: "Google Ads",
    status: "Lost",
    assignedTo: "Dinesh Kannan",
    enquiry: "Commercial showroom interior - Town Hall",
    createdAt: "2026-05-18",
    lastFollowUp: "2026-06-03",
    nextFollowUp: null,
    timeline: [
      tl("l15-1", "note", "Lead captured", "Google Ads enquiry for showroom interior", "2026-05-18T10:00:00"),
      tl("l15-2", "call", "Call made", "Discussed showroom interior scope", "2026-05-21T12:00:00"),
      tl("l15-3", "site-visit", "Site visit cancelled", "Client postponed project indefinitely", "2026-06-02T11:00:00"),
      tl("l15-4", "status", "Marked as Lost", "Project shelved by client", "2026-06-03T09:00:00"),
    ],
  },
  {
    id: "lead-16",
    name: "Swetha Balaji",
    phone: "+91 99765 65123",
    email: "swetha.balaji@gmail.com",
    location: "Saibaba Colony",
    source: "Website",
    status: "New",
    assignedTo: "Bharath Kumar",
    enquiry: "Modular kitchen - NRI client",
    createdAt: "2026-06-20",
    lastFollowUp: null,
    nextFollowUp: "2026-06-23",
    timeline: [
      tl("l16-1", "note", "Lead captured", "Website enquiry for modular kitchen, NRI client", "2026-06-20T11:00:00"),
    ],
  },
  {
    id: "lead-17",
    name: "Imran Sheikh",
    phone: "+91 90470 76234",
    email: "imran.sheikh@gmail.com",
    location: "Avinashi Road",
    source: "Walk-in",
    status: "Interested",
    assignedTo: "Yamini Sridhar",
    enquiry: "Office interior fit-out - Avinashi Road",
    createdAt: "2026-06-14",
    lastFollowUp: "2026-06-19",
    nextFollowUp: "2026-06-22",
    timeline: [
      tl("l17-1", "note", "Lead captured", "Walk-in enquiry for office interior fit-out", "2026-06-14T10:00:00"),
      tl("l17-2", "call", "Call made", "Discussed seating capacity and timeline", "2026-06-17T12:30:00"),
      tl("l17-3", "followup", "Follow-up added", "Shared office fit-out cost estimate", "2026-06-19T16:00:00"),
    ],
  },
  {
    id: "lead-18",
    name: "Deepa Chandran",
    phone: "+91 98940 87345",
    email: "deepa.chandran@gmail.com",
    location: "Saravanampatti",
    source: "WhatsApp",
    status: "Follow-up",
    assignedTo: "Praveen Anand",
    enquiry: "1200 sqft plot - Kovaipudur",
    createdAt: "2026-06-12",
    lastFollowUp: "2026-06-18",
    nextFollowUp: "2026-06-21",
    timeline: [
      tl("l18-1", "note", "Lead captured", "WhatsApp enquiry for 1200 sqft plot", "2026-06-12T09:00:00"),
      tl("l18-2", "call", "Call made", "Discussed plot location and pricing", "2026-06-14T11:30:00"),
      tl("l18-3", "followup", "Follow-up added", "Sent plot layout and EC documents", "2026-06-18T15:00:00"),
    ],
  },
];

export const FOLLOW_UPS: FollowUp[] = [
  { id: "fu-1", leadId: "lead-4", leadName: "Lakshmi Narayanan", executive: "Shobana Murali", priority: "Medium", dueDate: "2026-06-21", status: "Pending", remarks: "Confirm budget and floor preference" },
  { id: "fu-2", leadId: "lead-18", leadName: "Deepa Chandran", executive: "Praveen Anand", priority: "Low", dueDate: "2026-06-21", status: "Pending", remarks: "Send plot layout photos" },
  { id: "fu-3", leadId: "lead-8", leadName: "Revathi Ramesh", executive: "Praveen Anand", priority: "High", dueDate: "2026-06-20", status: "Overdue", remarks: "Discuss loan eligibility" },
  { id: "fu-4", leadId: "lead-13", leadName: "Naveen Prakash", executive: "Praveen Anand", priority: "Medium", dueDate: "2026-06-19", status: "Overdue", remarks: "Share resale flat documents" },
  { id: "fu-5", leadId: "lead-3", leadName: "Arun Raj", executive: "Praveen Anand", priority: "Medium", dueDate: "2026-06-22", status: "Pending", remarks: "Interior mood board walkthrough" },
  { id: "fu-6", leadId: "lead-6", leadName: "Divya Shankar", executive: "Bharath Kumar", priority: "Low", dueDate: "2026-06-22", status: "Pending", remarks: "Introductory call" },
  { id: "fu-7", leadId: "lead-9", leadName: "Vignesh Anand", executive: "Shobana Murali", priority: "Low", dueDate: "2026-06-23", status: "Pending", remarks: "Send renovation quote" },
  { id: "fu-8", leadId: "lead-11", leadName: "Suresh Babu", executive: "Bharath Kumar", priority: "Medium", dueDate: "2026-06-24", status: "Pending", remarks: "Studio apartment pricing discussion" },
  { id: "fu-9", leadId: "lead-17", leadName: "Imran Sheikh", executive: "Yamini Sridhar", priority: "High", dueDate: "2026-06-22", status: "Pending", remarks: "Office fit-out scope finalization" },
  { id: "fu-10", leadId: "lead-1", leadName: "Karthik Subramaniam", executive: "Bharath Kumar", priority: "High", dueDate: "2026-06-17", status: "Done", remarks: "Confirmed site visit date" },
  { id: "fu-11", leadId: "lead-2", leadName: "Priya Venkatesh", executive: "Yamini Sridhar", priority: "Medium", dueDate: "2026-06-14", status: "Done", remarks: "Final price negotiation - closed won" },
  { id: "fu-12", leadId: "lead-16", leadName: "Swetha Balaji", executive: "Bharath Kumar", priority: "Low", dueDate: "2026-06-23", status: "Pending", remarks: "Send modular kitchen catalogue" },
];

export const SITE_VISITS: SiteVisit[] = [
  { id: "sv-1", leadId: "lead-1", leadName: "Karthik Subramaniam", date: "2026-06-23", executive: "Bharath Kumar", status: "Scheduled", remarks: "Show 3BHK villa model unit" },
  { id: "sv-2", leadId: "lead-5", leadName: "Mohammed Faizal", date: "2026-06-24", executive: "Dinesh Kannan", status: "Scheduled", remarks: "Walkthrough villa interior samples" },
  { id: "sv-3", leadId: "lead-10", leadName: "Kavitha Raman", date: "2026-06-25", executive: "Dinesh Kannan", status: "Scheduled", remarks: "Gated community site tour" },
  { id: "sv-4", leadId: "lead-14", leadName: "Meena Sundaram", date: "2026-06-26", executive: "Shobana Murali", status: "Scheduled", remarks: "NRI client virtual + on-site visit" },
  { id: "sv-5", leadId: "lead-2", leadName: "Priya Venkatesh", date: "2026-06-12", executive: "Yamini Sridhar", status: "Completed", remarks: "Site visit done, client loved the flat" },
  { id: "sv-6", leadId: "lead-15", leadName: "Rajesh Gounder", date: "2026-06-02", executive: "Dinesh Kannan", status: "Cancelled", remarks: "Client postponed indefinitely" },
  { id: "sv-7", leadId: "lead-12", leadName: "Anitha Krishnan", date: "2026-06-10", executive: "Yamini Sridhar", status: "Completed", remarks: "Interior site measurement completed" },
  { id: "sv-8", leadId: "lead-8", leadName: "Revathi Ramesh", date: "2026-06-27", executive: "Praveen Anand", status: "Scheduled", remarks: "Independent house site visit - Vadavalli" },
];

export const DASHBOARD_ACTIVITY_LEAD_IDS = [
  "lead-1",
  "lead-2",
  "lead-3",
  "lead-4",
  "lead-5",
  "lead-8",
  "lead-10",
  "lead-13",
];

export const MONTHLY_CONVERSIONS = [
  { month: "Jan", conversions: 4 },
  { month: "Feb", conversions: 6 },
  { month: "Mar", conversions: 5 },
  { month: "Apr", conversions: 8 },
  { month: "May", conversions: 7 },
  { month: "Jun", conversions: 9 },
];

export const FOLLOWUP_PERFORMANCE = [
  { day: "Jun 15", completed: 5, missed: 2 },
  { day: "Jun 16", completed: 7, missed: 1 },
  { day: "Jun 17", completed: 6, missed: 3 },
  { day: "Jun 18", completed: 8, missed: 1 },
  { day: "Jun 19", completed: 7, missed: 2 },
  { day: "Jun 20", completed: 9, missed: 1 },
  { day: "Jun 21", completed: 6, missed: 2 },
];

export const REPORTS_STATS = {
  totalCalls: 142,
  connectedCalls: 98,
  followUpsDone: 64,
  siteVisits: 21,
  conversions: 9,
};

export const CALLS_VS_CONNECTED = [
  { day: "Mon", calls: 22, connected: 16 },
  { day: "Tue", calls: 19, connected: 13 },
  { day: "Wed", calls: 25, connected: 18 },
  { day: "Thu", calls: 21, connected: 14 },
  { day: "Fri", calls: 28, connected: 20 },
  { day: "Sat", calls: 17, connected: 11 },
  { day: "Sun", calls: 10, connected: 6 },
];

export const CONVERSION_FUNNEL = [
  { stage: "Leads", value: 18 },
  { stage: "Interested", value: 11 },
  { stage: "Site Visit", value: 7 },
  { stage: "Won", value: 2 },
];

export const WEEKLY_ACTIVITY_TREND = [
  { week: "Week 1", activities: 38 },
  { week: "Week 2", activities: 45 },
  { week: "Week 3", activities: 41 },
  { week: "Week 4", activities: 52 },
];
